apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocm-managed-serviceaccount-replicaset-controller-leader-election
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
