apiVersion: authentication.appthrust.io/v1alpha1
kind: ManagedServiceAccountSet
metadata:
  name: aws-workload-identity-operator
  namespace: appthrust-system
spec:
  placement:
    clusterSets:
      - workload
    selector:
      matchLabels:
        role.appthrust.io/workload-cluster: "true"
  managedServiceAccount:
    name: aws-workload-identity-operator
    credentialPublication: ClusterProfile
    rotation:
      enabled: true
      validity: 8640h
  remotePermissions:
    enabled: true
    profileRefs:
      - name: aws-workload-identity-selfhosted-irsa
    remoteServiceAccountNamespace: open-cluster-management-managed-serviceaccount

