//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildObjectReference) DeepCopyInto(out *ChildObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildObjectReference.
func (in *ChildObjectReference) DeepCopy() *ChildObjectReference {
	if in == nil {
		return nil
	}
	out := new(ChildObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFailure) DeepCopyInto(out *ClusterFailure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFailure.
func (in *ClusterFailure) DeepCopy() *ClusterFailure {
	if in == nil {
		return nil
	}
	out := new(ClusterFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSummary) DeepCopyInto(out *ClusterSummary) {
	*out = *in
	if in.ManagedServiceAccountRef != nil {
		in, out := &in.ManagedServiceAccountRef, &out.ManagedServiceAccountRef
		*out = new(ChildObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSummary.
func (in *ClusterSummary) DeepCopy() *ClusterSummary {
	if in == nil {
		return nil
	}
	out := new(ClusterSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPlacementReference) DeepCopyInto(out *LocalPlacementReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPlacementReference.
func (in *LocalPlacementReference) DeepCopy() *LocalPlacementReference {
	if in == nil {
		return nil
	}
	out := new(LocalPlacementReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceAccountRotation) DeepCopyInto(out *ManagedServiceAccountRotation) {
	*out = *in
	if in.Validity != nil {
		in, out := &in.Validity, &out.Validity
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceAccountRotation.
func (in *ManagedServiceAccountRotation) DeepCopy() *ManagedServiceAccountRotation {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceAccountRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceAccountSet) DeepCopyInto(out *ManagedServiceAccountSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceAccountSet.
func (in *ManagedServiceAccountSet) DeepCopy() *ManagedServiceAccountSet {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceAccountSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedServiceAccountSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceAccountSetList) DeepCopyInto(out *ManagedServiceAccountSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedServiceAccountSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceAccountSetList.
func (in *ManagedServiceAccountSetList) DeepCopy() *ManagedServiceAccountSetList {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceAccountSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedServiceAccountSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceAccountSetPlacement) DeepCopyInto(out *ManagedServiceAccountSetPlacement) {
	*out = *in
	if in.ClusterSets != nil {
		in, out := &in.ClusterSets, &out.ClusterSets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceAccountSetPlacement.
func (in *ManagedServiceAccountSetPlacement) DeepCopy() *ManagedServiceAccountSetPlacement {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceAccountSetPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceAccountSetSpec) DeepCopyInto(out *ManagedServiceAccountSetSpec) {
	*out = *in
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(ManagedServiceAccountSetPlacement)
		(*in).DeepCopyInto(*out)
	}
	if in.PlacementRef != nil {
		in, out := &in.PlacementRef, &out.PlacementRef
		*out = new(LocalPlacementReference)
		**out = **in
	}
	in.ManagedServiceAccount.DeepCopyInto(&out.ManagedServiceAccount)
	if in.RemotePermissions != nil {
		in, out := &in.RemotePermissions, &out.RemotePermissions
		*out = new(RemotePermissionsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceAccountSetSpec.
func (in *ManagedServiceAccountSetSpec) DeepCopy() *ManagedServiceAccountSetSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceAccountSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceAccountSetStatus) DeepCopyInto(out *ManagedServiceAccountSetStatus) {
	*out = *in
	if in.PlacementRef != nil {
		in, out := &in.PlacementRef, &out.PlacementRef
		*out = new(LocalPlacementReference)
		**out = **in
	}
	if in.FailedClusters != nil {
		in, out := &in.FailedClusters, &out.FailedClusters
		*out = make([]ClusterFailure, len(*in))
		copy(*out, *in)
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceAccountSetStatus.
func (in *ManagedServiceAccountSetStatus) DeepCopy() *ManagedServiceAccountSetStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceAccountSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceAccountTemplate) DeepCopyInto(out *ManagedServiceAccountTemplate) {
	*out = *in
	in.Rotation.DeepCopyInto(&out.Rotation)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceAccountTemplate.
func (in *ManagedServiceAccountTemplate) DeepCopy() *ManagedServiceAccountTemplate {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceAccountTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionProfileReference) DeepCopyInto(out *PermissionProfileReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionProfileReference.
func (in *PermissionProfileReference) DeepCopy() *PermissionProfileReference {
	if in == nil {
		return nil
	}
	out := new(PermissionProfileReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemotePermissionsSpec) DeepCopyInto(out *RemotePermissionsSpec) {
	*out = *in
	if in.ProfileRefs != nil {
		in, out := &in.ProfileRefs, &out.ProfileRefs
		*out = make([]PermissionProfileReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemotePermissionsSpec.
func (in *RemotePermissionsSpec) DeepCopy() *RemotePermissionsSpec {
	if in == nil {
		return nil
	}
	out := new(RemotePermissionsSpec)
	in.DeepCopyInto(out)
	return out
}
